### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by Pentagrade** [cccsdh/NLog.LiteDB#2]
Hi, I've been trying to setup LiteDB Nlogging but cant seem to get it to write out. I have tried copying the example config in the repo just in case of typos but no joy. I activated the internal log and have found an error occurring as follows:
```
2018-08-30 11:11:58.0487 Error Error when writing to LiteDB System.MissingMethodException: Method not found: 'Void LiteDB.LiteDatabase..ctor(System.String, LiteDB.BsonMapper)'.
   at NLog.LiteDB.LiteDBTarget.<GetCollection>b__42_0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NLog.LiteDB.LiteDBTarget.GetCollection()
   at NLog.LiteDB.LiteDBTarget.Write(LogEventInfo logEvent)
```
Any ideas?

**Comment by cccsdh** [comment]
Have you tried looking at the spec project?   The base integration test is working with the NuGet package versions listed.   I updated them all to the latest versions of the packages and the integration test still executes.    Possibly you can attach the code you are trying to setup and I will examine to see if I can see what issue you are having.

**Comment by cccsdh** [comment]
[LiteDB_NLog_Example.zip](https://github.com/cccsdh/NLog.LiteDB/files/2340257/LiteDB_NLog_Example.zip)
Here's a simple example of using the Nlog target in an application.

**Comment by snakefoot** [comment]
There is a breaking change in LiteDB here: https://github.com/mbdavid/LiteDB/commit/5acd303abce92cf24b9cfac2bdd8b709fcaa26b2#diff-df389abff6d3dc434933ac4d4bb7e07b (Parameter added to constructor). So unless using LiteDb ver. 3.1.0, then you need to recompile the LiteDBTarget yourself to handle this breaking change.

**Comment by Pentagrade** [comment]
Thanks for the input, I will review this next week and see what I can come up with.

**Comment by snakefoot** [comment]
@cccsdh Any reason for updating NetFramework and NLog-version? Would probably be better that this target upgraded to latest LiteDB (Ex [ver.  4.1.4](https://www.nuget.org/packages/LiteDB/))

**Comment by cccsdh** [comment]
It will eventually upgrade to 4.1.4, however this update brings it to the release with the breaking change.   Once that rolls to Nuget - the next release will upgrade to the latest LiteDB.

**Comment by cccsdh** [comment]
Repository is now current with LiteDB version as well - Moved from MyGet to VSTS for continuous integration so that Nuget pushes happen each build - versus once a week.

Marking the issue closed
