### ISSUE TITLE
how read full log!?

### ISSUE THREAD

**Issue by ggiacomoo** [cccsdh/NLog.LiteDB#4]
how can i read a log with _id, properties and exception ?

and which is best way for a sorting (example by _id asc/desc) ?

thanks

**Comment by cccsdh** [comment]
The question really is not an NLog.LiteDB target question.   You are really asking specific LiteDB information

https://github.com/mbdavid/LiteDB/wiki - has a lot about just accessing the data.

For our example - 


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LiteDB;

namespace ExampleApp
{
	public class DefaultLog
	{
		public ObjectId Id { get; set; }
		public int ThreadID { get; set; }
		public string ThreadName { get; set; }
		public int ProcessID { get; set; }
		public string ProcessName { get; set; }
		public string UserName { get; set; }
		public string Level { get; set; }
		public string Message { get; set; }
	}
}

If you change the DefaultLog class as above - the ID will be added to the object returned in the Program Class:

using System;
using System.Collections.Generic;
using System.Linq;
using NLog;

namespace ExampleApp
{
	class Program
	{
		private readonly static Logger _logger = LogManager.GetCurrentClassLogger();
		static void Main(string[] args)
		{
			_logger.Info($"Start of application at {DateTime.Now.ToString("HH.mm.ss")}");

			DisplayLog();
			Console.ReadLine();

		}
		static void DisplayLog()
		{
			var db = new LiteDB.LiteDatabase("filename=Example_Nlog.db");

			var collection = db.GetCollection<DefaultLog>("DefaultLog");
			Console.WriteLine($"There are {collection.Count()} log entries in collection");


			var entries = collection.FindAll().ToList();

			List<DefaultLog> SortedList = entries.OrderBy(o => o.Id).ToList();

			foreach (var item in SortedList)
			{
				Console.WriteLine($"{item.Id} {item.Level}  {item.Message}");
			}

		}
	}
}

Note: 			var entries = collection.FindAll().ToList(); returns the full log - this is just standard LiteDB

			List<DefaultLog> SortedList = entries.OrderBy(o => o.Id).ToList(); - this sorts by Id of the DefaultLog collection.
