### ISSUE TITLE
DataDirectory placeholder in connection string

### ISSUE THREAD

**Issue by Ale64** [cccsdh/NLog.LiteDB#5]
Please support for the |DataDirectory| substitution string in connection strings. See this: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/connection-strings
and this topic: https://stackoverflow.com/questions/1833640/connection-string-with-relative-path-to-the-database-file

**Comment by cccsdh** [comment]
So, just want to remind you that this project is an NLog target for the LiteDB database, the first link provided is irrelevant. as it deals with Entityframework, and being a NoSQL database you would not utilize EF.   

The other link does bring up the concept of allowing for specifying 'special folders' in the LiteDB connection string, possibly implementing something that could take advantage of https://github.com/nlog/NLog/wiki/Special-Folder-Layout-Renderer.   I'll pin this for review.

**Comment by Ale64** [comment]
Special Folder is exactly what I need. Unfortunately it doesn't work for connection strings.

Here is my target config:

```
<target name="liteDB" xsi:type="liteDBTarget"
        connectionString="filename=${specialfolder:folder=LocalApplicationData}/my-log.db"
        collectionName="DefaultLog">
    <property name="ThreadID" layout="${threadid}" bsonType="Int32" />
    ...
</target>
```
And NLog inner-log:

> 2019-02-22 12:11:56.9123 Error Error when writing to LiteDB **System.NotSupportedException: The given path's format is not supported.**
>    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>    at LiteDB.FileDiskService.Initialize(Logger log, String password)
>    at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable\`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
>    at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
>    at LiteDB.LazyLoad\`1.get_Value()
>    at LiteDB.LiteCollection\`1.Insert(T document)
>    at NLog.LiteDB.LiteDBTarget.Write(LogEventInfo logEvent)
>

**Comment by Ale64** [comment]
Seems LiteDBTarget.ConnectionString property should be of Layout type.

**Comment by cccsdh** [comment]
Per my original email.  The underlying code will need to change.   Hence pinned for review.

**Comment by cccsdh** [comment]
I've created a development branch containing the changes for special folders.   

To answer your question on layout type.  First just some basic information.

A LiteDB connection string is nothing more than a string with that identifies a file (with or without a path).   So, defining the ConnectionString property as a layout would also require that some of the internal NLog processes be publically accessible.   However, that is not the case.

So - to support various definitions, we've established 3 connection string types:   Special, Path and File.  The markdown has been updated  to reflect these and the Spec project and Example Application have also been updated.

Once I'm satisfied that the changes are how we  want to address this issue - then we will merge the updates with the Master branch.

Please feel free to pull the development branch and test.

**Comment by cccsdh** [comment]
Changes have been pushed to Master.   Closing out this issue.
